version: '3.3'

services:
  mongodb:
    image: mongo:3.6.3-jessie
    environment:
      - MONGODB_DATA_DIR=/data/db
      - MONGODB_LOG_DIR=/dev/null
      - MONGODB_USER="mouse"
      - MONGODB_PASS="123qwe"
    volumes:
      - ./data-mongo/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
  app:
    image: node:8.9.4
    environment:
      - "TZ=Asia/Bangkok"
    volumes:
      - ./:/var/www/html/app
    links:
      - mongodb
    depends_on:
      - mongodb
    working_dir: /var/www/html/app
    command: >
       bash -c "npm install && npm install -g gulp@3.9.0 && gulp"
    ports:
      - 3000:3000
  nginx:
    image: nginx:1.13.8
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - app
    ports:
      - 80:80
volumes:
  learn-english:
